"""Event vocabulary for the scoring engine.

Everything that happens in a match is one of these events, appended to a log.
Match state is `fold(config, teams, events)` — see `engine.py`.

Deliberately absent: GAME_START and SIDE_SWITCH. Both are *derived* by the fold
when a game completes or a team reaches the midpoint. Keeping structural
transitions out of the log is what makes UNDO clean: undoing the first rally of
game 3 can't strand a half-applied "game 3 started" event.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict

Team = Literal["A", "B"]
Side = Literal["R", "L"]
Format = Literal["singles", "doubles"]
ScoringMode = Literal["sideout", "rally"]
SwitchEndsRule = Literal["never", "deciding_game", "every_game"]
FirstServerRule = Literal["alternate", "winner", "loser"]


class EventType(StrEnum):
    #: The serving side won the rally.
    RALLY_WON = "RALLY_WON"
    #: The serving side lost the rally (fault / side out).
    RALLY_LOST = "RALLY_LOST"
    TIMEOUT = "TIMEOUT"
    TECHNICAL_WARNING = "TECHNICAL_WARNING"
    #: Pops the most recent undoable event. No redo.
    UNDO = "UNDO"
    #: Override who serves first in the current game (deciding-game coin toss).
    #: Only legal while the current game is still at 0-0.
    SET_FIRST_SERVER = "SET_FIRST_SERVER"
    #: Abandon the match; score stands, no winner recorded.
    END_EARLY = "END_EARLY"
    #: Named team forfeits; the opponent is recorded as the winner.
    FORFEIT = "FORFEIT"


#: Events an UNDO is allowed to pop. END_EARLY and FORFEIT are terminal — to
#: reverse those, an organizer reopens the match rather than undoing.
UNDOABLE: frozenset[EventType] = frozenset(
    {
        EventType.RALLY_WON,
        EventType.RALLY_LOST,
        EventType.TIMEOUT,
        EventType.TECHNICAL_WARNING,
        EventType.SET_FIRST_SERVER,
    }
)


class Event(BaseModel):
    """A single entry in a match's append-only log.

    `client_event_id` is generated by the client so a retried batch is
    idempotent; `seq` is the client's monotonic counter so the server can detect
    gaps and reordering. Both are populated by the transport layer, not the
    engine — the engine only reads `type` and `team`.
    """

    model_config = ConfigDict(extra="forbid")

    type: EventType
    #: Required for TIMEOUT, TECHNICAL_WARNING, FORFEIT and SET_FIRST_SERVER.
    team: Team | None = None

    client_event_id: str | None = None
    seq: int | None = None
    actor_id: str | None = None
    created_at: str | None = None


class InvalidEvent(Exception):
    """Raised when an event cannot legally be applied to the current state."""


def resolve_undos(events: list[Event]) -> list[Event]:
    """Collapse UNDO events into the effective event sequence.

    Each UNDO pops the most recent *undoable* event that has not already been
    popped. Consecutive UNDOs walk further back. There is no redo, which matches
    the prototype's undo-stack behaviour.
    """
    effective: list[Event] = []
    for event in events:
        if event.type is not EventType.UNDO:
            effective.append(event)
            continue
        for i in range(len(effective) - 1, -1, -1):
            if effective[i].type in UNDOABLE:
                del effective[i]
                break
        # An UNDO with nothing to pop is a no-op rather than an error: a
        # double-tap on a fresh game shouldn't fail a whole sync batch.
    return effective
