"""initial schema

Revision ID: 519d0b77f31e
Revises: 
Create Date: 2026-08-11 19:39:57.882372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString in autogenerated scripts.
import sqlmodel
# JSONB variants render as `postgresql.JSONB(astext_type=Text())`.
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '519d0b77f31e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZER', 'SCOREKEEPER', 'PLAYER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('players',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_owner_id'), 'players', ['owner_id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ends_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION', 'LIVE', 'COMPLETE', name='tournamentstatus'), nullable=False),
    sa.Column('public_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_owner_id'), 'tournaments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tournaments_public_token'), 'tournaments', ['public_token'], unique=True)
    op.create_index(op.f('ix_tournaments_slug'), 'tournaments', ['slug'], unique=True)
    op.create_table('courts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tournament_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_USE', 'CLOSED', name='courtstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_tournament_id'), 'courts', ['tournament_id'], unique=False)
    op.create_table('divisions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tournament_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sa.Enum('SINGLES', 'DOUBLES', 'MIXED', name='divisionformat'), nullable=False),
    sa.Column('skill_bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age_bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draw_kind', sa.Enum('ROUND_ROBIN', 'SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'POOL_PLAYOFF', name='drawkind'), nullable=False),
    sa.Column('draw_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('match_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tiebreakers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('draw_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_tournament_id'), 'divisions', ['tournament_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'CHECKED_IN', 'WITHDRAWN', name='entrystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_division_id'), 'entries', ['division_id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('pools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_division_id'), 'stages', ['division_id'], unique=False)
    op.create_table('entry_players',
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'player_id')
    )
    op.create_table('matches',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draw_match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('pool', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conditional', sa.Boolean(), nullable=False),
    sa.Column('decides_title', sa.Boolean(), nullable=False),
    sa.Column('entry_a_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_b_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_a', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_b', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('bye_a', sa.Boolean(), nullable=False),
    sa.Column('bye_b', sa.Boolean(), nullable=False),
    sa.Column('court_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'LIVE', 'COMPLETE', 'BYE', 'SKIPPED', 'ABANDONED', name='matchstatus'), nullable=False),
    sa.Column('winner_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scorekeeper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_server', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_a_id'], ['entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_b_id'], ['entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scorekeeper_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_entry_id'], ['entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division_id', 'draw_match_id', name='uq_match_draw_slot')
    )
    op.create_index(op.f('ix_matches_court_id'), 'matches', ['court_id'], unique=False)
    op.create_index(op.f('ix_matches_division_id'), 'matches', ['division_id'], unique=False)
    op.create_index(op.f('ix_matches_draw_match_id'), 'matches', ['draw_match_id'], unique=False)
    op.create_index(op.f('ix_matches_stage_id'), 'matches', ['stage_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'game_number', name='uq_game_number')
    )
    op.create_index(op.f('ix_games_match_id'), 'games', ['match_id'], unique=False)
    op.create_table('rally_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('client_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'client_event_id', name='uq_event_client_id'),
    sa.UniqueConstraint('match_id', 'seq', name='uq_event_seq')
    )
    op.create_index(op.f('ix_rally_events_match_id'), 'rally_events', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rally_events_match_id'), table_name='rally_events')
    op.drop_table('rally_events')
    op.drop_index(op.f('ix_games_match_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_stage_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_draw_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_division_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_court_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('entry_players')
    op.drop_index(op.f('ix_stages_division_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_entries_division_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_divisions_tournament_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_courts_tournament_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_tournaments_slug'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_public_token'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_owner_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_owner_id'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
