"""initial schema

Revision ID: 98dfaa03828b
Revises: 
Create Date: 2026-08-11 16:10:54.740204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98dfaa03828b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZER', 'SCOREKEEPER', 'PLAYER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('players',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=False)

    op.create_table('tournaments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ends_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION', 'LIVE', 'COMPLETE', name='tournamentstatus'), nullable=False),
    sa.Column('public_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_tournaments_slug'), ['slug'], unique=True)

    op.create_table('courts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tournament_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_USE', 'CLOSED', name='courtstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courts_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('divisions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tournament_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sa.Enum('SINGLES', 'DOUBLES', 'MIXED', name='divisionformat'), nullable=False),
    sa.Column('skill_bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age_bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draw_kind', sa.Enum('ROUND_ROBIN', 'SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'POOL_PLAYOFF', name='drawkind'), nullable=False),
    sa.Column('draw_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('match_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tiebreakers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('draw_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_divisions_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'CHECKED_IN', 'WITHDRAWN', name='entrystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_division_id'), ['division_id'], unique=False)

    op.create_table('stages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('pools', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_division_id'), ['division_id'], unique=False)

    op.create_table('entry_players',
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'player_id')
    )
    op.create_table('matches',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draw_match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('pool', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conditional', sa.Boolean(), nullable=False),
    sa.Column('decides_title', sa.Boolean(), nullable=False),
    sa.Column('entry_a_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_b_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_a', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_b', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('bye_a', sa.Boolean(), nullable=False),
    sa.Column('bye_b', sa.Boolean(), nullable=False),
    sa.Column('court_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'LIVE', 'COMPLETE', 'BYE', 'SKIPPED', 'ABANDONED', name='matchstatus'), nullable=False),
    sa.Column('winner_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scorekeeper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('first_server', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['entry_a_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['entry_b_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['scorekeeper_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['winner_entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division_id', 'draw_match_id', name='uq_match_draw_slot')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_draw_match_id'), ['draw_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    op.create_table('games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'game_number', name='uq_game_number')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_match_id'), ['match_id'], unique=False)

    op.create_table('rally_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('client_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'client_event_id', name='uq_event_client_id'),
    sa.UniqueConstraint('match_id', 'seq', name='uq_event_seq')
    )
    with op.batch_alter_table('rally_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rally_events_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rally_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rally_events_match_id'))

    op.drop_table('rally_events')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_match_id'))

    op.drop_table('games')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_stage_id'))
        batch_op.drop_index(batch_op.f('ix_matches_draw_match_id'))
        batch_op.drop_index(batch_op.f('ix_matches_division_id'))
        batch_op.drop_index(batch_op.f('ix_matches_court_id'))

    op.drop_table('matches')
    op.drop_table('entry_players')
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_division_id'))

    op.drop_table('stages')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_division_id'))

    op.drop_table('entries')
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divisions_tournament_id'))

    op.drop_table('divisions')
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courts_tournament_id'))

    op.drop_table('courts')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_slug'))
        batch_op.drop_index(batch_op.f('ix_tournaments_public_token'))
        batch_op.drop_index(batch_op.f('ix_tournaments_owner_id'))

    op.drop_table('tournaments')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.drop_index(batch_op.f('ix_players_owner_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
